Контроллер игрока
DreamFlightStudios/Planet-Adventure pull request #2
Opened 2024-04-29 18:37 UTC by DreamFlightStudios

колизия камер, аниматор, сам контроллер, контроллер камеры

2024-04-29 19:14 UTC, Hitsar requested changes
лень проверять контролер игрока, выглядит нормально так что верю на слово

2024-04-29 19:14 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/CameraCollision.cs
> +    private void LateUpdate()
физика в апдейте
если в фиксед будет дёргаться то пофиг

2024-04-29 19:14 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    public override event Action<float, float> Moved;
если нифига не поменялось зачем оверайдить

2024-04-29 19:14 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    private void Awake() => _playerInput = new PlayerInput();
сделай какой нибуть сервис локатор или di прикрути. инпут 1 на всю игру, да и удобнее будет в принцепе с этим

2024-04-29 20:14 UTC, DreamFlightStudios commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    private void Awake() => _playerInput = new PlayerInput();
ты про зенжект?

2024-04-29 20:29 UTC, DreamFlightStudios commented on Assets/Project/Scripts/PlayerController/CameraCollision.cs
> +    private void LateUpdate()
в апдейт перенести?

2024-04-30 17:10 UTC, DreamFlightStudios commented on Assets/Project/Scripts/PlayerController/CameraCollision.cs
> +    private void LateUpdate()
или ты про что

2024-04-30 18:39 UTC, DreamFlightStudios commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    public override event Action<float, float> Moved;
оно ругается если не оверрайд

2024-04-30 19:08 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    public override event Action<float, float> Moved;
потому что ты его абстрактным в классе сделал

2024-04-30 19:08 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    public override event Action<float, float> Moved;
потому что ты его абстрактным в классе сделал

2024-04-30 19:08 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/CameraCollision.cs
> +    private void LateUpdate()
3 слово на 2 строчке прочитай

2024-04-30 19:09 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    private void Awake() => _playerInput = new PlayerInput();
погугли что такое сервис локатор и di

2024-04-30 19:15 UTC, DreamFlightStudios commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +    private void Awake() => _playerInput = new PlayerInput();
в прошлый раз ты меня застваил зенджект добавить

2024-05-06 07:58 UTC, Hitsar requested changes

2024-05-06 07:58 UTC, Hitsar commented on Assets/Project/Scripts/AnimationObject.cs
нафиг тебе его вобще переопределять я не пойму, у тебя ничего не поменяется
так же это MovingObject a не AnimationObject

2024-05-06 07:58 UTC, Hitsar commented on Assets/Project/Scripts/Instaillers/GlobalInstaller.cs
> +        Container.Bind<ThirdPersonController>().AsSingle();
а оно работает? если да то можешь закрывать это

2024-05-06 07:58 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/CameraController.cs
> +    private void Awake() => _playerInput = new PlayerInput();
нафиг тебе зенджект тогда

2024-05-06 07:58 UTC, Hitsar commented on Assets/Project/Scripts/PlayerController/ThirdPersonController.cs
> +        if (_inputDirection.magnitude > 0f) Rotate();
оптимизированей будет квадрат магнитуды использовать, попробуй

2024-05-06 08:20 UTC, DreamFlightStudios commented on Assets/Project/Scripts/AnimationObject.cs
хз, там какая то ошибка появляется 
почему мувинг обджект, если класс для анимированных объектов, я хотел как интерфейс сделать, но он в инспекторе не отображается

2024-05-10 12:16 UTC, Hitsar requested changes
пробелы лишние убери и header тебе нафиг ненужон ради 1 поля, но это по желанию

2024-05-10 12:16 UTC, Hitsar commented on Assets/Project/Scripts/Animations/IAnimationObject.cs
интерфейс отвечает на вопрос "какой?" IAnimated (object писать не обязательно думаю)

2024-05-12 17:37 UTC, merged