взаимодействие с предметами
DreamFlightStudios/Planet-Adventure pull request #4
Opened 2024-05-18 08:42 UTC by DreamFlightStudios

сделал интервейс предметов, с котлрыми можно взаимодействоать, добавл скрипт Hand, и класс подбиравемого предмета

2024-05-18 10:40 UTC, Hitsar requested changes
у меня теперь 2 папки Scripts, давай лучше одну

2024-05-18 10:40 UTC, Hitsar commented on Assets/Project/Characters/Player/Scripts/Interaction/IInteraction.cs
> +public interface IInteraction
какой - interactive

2024-05-18 10:40 UTC, Hitsar commented on Assets/Project/Characters/Player/Scripts/Interaction/Hand.cs
> +        IInteraction interactionObject = triggerObject?.GetComponent<IInteraction>();
а если нет компонента IInteraction? будет ошибка. используй TryGetComponent
triggerObject? значит у тебя он может быть null? и к gameObject это не применяется

2024-05-18 10:40 UTC, Hitsar commented on Assets/Project/Characters/Player/Scripts/Interaction/PickUpObject.cs
> +    public bool CanInteract() => _canInteract;
не увидел где это используется, зачем это?

2024-05-19 13:36 UTC, Hitsar requested changes

2024-05-19 13:36 UTC, Hitsar commented on Assets/Project/Scripts/Player/Interaction/Hand.cs
> +    private void OnTriggerExit(Collider other) => OnTrigger(false, other.gameObject);
здесь у тебя только `_interactionObject = null;` сработает, поэтому нет смысла вызывать метод где проверка в любом случае не пройдёт. это одна строчка не такой уж и дубляж, а лишняя проверка уже ух

2024-05-19 13:36 UTC, Hitsar commented on Assets/Project/Scripts/Player/Interaction/PickUpObject.cs
> +    public bool CanInteract() => _canInteract;
думаю эти 2 строчки можно заменить на публичное свойство private set, что бы в инспекотре отобразить напиши [field: SerializeField]

2024-05-19 17:21 UTC, DreamFlightStudios commented on Assets/Project/Scripts/Player/Interaction/PickUpObject.cs
> +    public bool CanInteract() => _canInteract;
![image](https://github.com/DreamFlightStudios/Planet-Adventure/assets/127213451/afe47c22-dca4-4184-a068-4f23a36f3519)

2024-05-19 17:27 UTC, DreamFlightStudios commented on Assets/Project/Scripts/Player/Interaction/Hand.cs
> +    private void OnTriggerExit(Collider other) => OnTrigger(false, other.gameObject);
там нужно обнулять интеректион обджект если фалс, можно переопределение метода сделать, но слишком много мороки мне кажется

2024-05-23 05:05 UTC, Hitsar requested changes

2024-05-23 05:05 UTC, Hitsar commented on Assets/Project/Scripts/Player/Interaction/Hand.cs
> +    private void OnTrigger(bool onEnter, GameObject triggerObject)
Теперь не понятно почему это у тебя в отдельном методе. Если б было сразу то ты бы увидел что от book onEnter смысла нет

2024-05-27 11:12 UTC, Hitsar requested changes
Чё?

2024-05-27 11:12 UTC, Hitsar commented on Assets/Project/Scripts/Player/Interaction/Hand.cs
> +    private void OnTrigger(GameObject triggerObject)
Не обязательно в отдельный метод выносить весь код который только в 1 пустом месте используется

2024-05-28 14:20 UTC, Hitsar requested changes

2024-05-28 14:20 UTC, Hitsar commented on Assets/Project/Scripts/Player/Interaction/Hand.cs
> +    private void AddItem()
Мне мерджить пустой метод?

2024-06-01 10:06 UTC, merged